
package lk.ijse.bus_seat_reservation.view;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.bus_seat_reservation.controller.AllDetailsController;
import lk.ijse.bus_seat_reservation.modal.PassengerInformation;
import lk.ijse.bus_seat_reservation.modal.Reservation;

/**
 *
 * @author vimukthi
 */
public class AllDetails extends javax.swing.JFrame {

    public AllDetails() {
        initComponents();
        loadAllDetails();
        
         JLabel[] lbl={lblRegistration,lblBus,lblPassenger,lblReport,lblBusDetailes,lblPassengerDetailes};
        for (JLabel jLabel : lbl) {
                jLabel.setBackground(new Color(0,0,0));
                jLabel.setOpaque(true);
                jLabel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {  
                    }
                    @Override
                    public void mousePressed(MouseEvent e) { 
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) { 
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                       jLabel.setBackground(new Color(45, 51, 61));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                       jLabel.setBackground(new Color(0,0,0));
                    }
                });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        lblBus = new javax.swing.JLabel();
        lblPassenger = new javax.swing.JLabel();
        lblBusDetailes = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblPassengerDetailes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSeacrh = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 39, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/image/buslogo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 180));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Registration_45px.png"))); // NOI18N
        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });
        jPanel8.add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 70));

        lblBus.setForeground(new java.awt.Color(255, 255, 255));
        lblBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Home_45px_1.png"))); // NOI18N
        lblBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusMouseClicked(evt);
            }
        });
        jPanel8.add(lblBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 70));

        lblPassenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Ticket_Purchase_45px.png"))); // NOI18N
        lblPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 70));

        lblBusDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Bus_43px.png"))); // NOI18N
        lblBusDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblBusDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 70));

        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Numbered_List_45px.png"))); // NOI18N
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });
        jPanel8.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 70));

        lblPassengerDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassengerDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_User_Account_45px_1.png"))); // NOI18N
        lblPassengerDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassengerDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, 70));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 540));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 540));

        jPanel3.setBackground(new java.awt.Color(34, 39, 46));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(34, 39, 46));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 204, 204));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel5.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 640, 170, 40));

        jPanel7.setBackground(new java.awt.Color(45, 51, 61));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 340, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Reservation Details");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 80));

        txtSeacrh.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.add(txtSeacrh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 870, 40));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(204, 204, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Id", "Seat Id", "passenger Name", "NIC", "Date", "Phone", "dsdsd", "sds"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1060, 400));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1160, 720));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
        new RegistrationFormView().setVisible(true);
    }//GEN-LAST:event_lblRegistrationMouseClicked

    private void lblBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusMouseClicked
        new DashBoardView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBusMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    new TicketBookingView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    }//GEN-LAST:event_btnSearchActionPerformed

    private void lblBusDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusDetailesMouseClicked
       new BusDetailesView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblBusDetailesMouseClicked

    private void lblPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerMouseClicked
        new TicketBookingView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPassengerMouseClicked

    private void lblPassengerDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerDetailesMouseClicked
       new PassengerDetailesView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblPassengerDetailesMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        this.setVisible(true);
    }//GEN-LAST:event_lblReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBus;
    private javax.swing.JLabel lblBusDetailes;
    private javax.swing.JLabel lblPassenger;
    private javax.swing.JLabel lblPassengerDetailes;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTextField txtSeacrh;
    // End of variables declaration//GEN-END:variables

    private void loadAllDetails() {
        
        try {
            DefaultTableModel modal=(DefaultTableModel) jTable1.getModel();
            
            List<Reservation> reservation=new AllDetailsController().getAllReservation();
            
             for(Reservation tempPatient:reservation){
                
                modal.addRow(new Object[]{
                tempPatient.getReservation_id(),
                tempPatient.getOfficer_id(),
                tempPatient.getPassenger_id(),
                tempPatient.getReservation_date()               
                });
                
            }
            
            List<PassengerInformation> patientList=new AllDetailsController().getAllPassenger();
            
            //DefaultTableModel modal=(DefaultTableModel) jTable1.getModel();
            
            for(PassengerInformation tempPatient:patientList){
                
                modal.addRow(new Object[]{
                tempPatient.getPassenger_id(),
                tempPatient.getName(),
                tempPatient.getNic(),
                tempPatient.getPhone_number()               
                });
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AllDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  
}
