
package lk.ijse.bus_seat_reservation.view;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import lk.ijse.bus_seat_reservation.controller.DashBoardController;

/**
 *
 * @author vimukthi
 */
public class DashBoardView extends javax.swing.JFrame {

    public DashBoardView() {
        initComponents();
        loadAllPassengerCount();
        loadAllBusCount();
        loadAllEarningCount();
        
        JLabel[] lbl={lblRegistration,lblBus,lblPassenger,lblReport,lblPassengerDetailes,lblBusDetailes};
        for (JLabel jLabel : lbl) {
                jLabel.setBackground(new Color(0,0,0));
                jLabel.setOpaque(true);
                jLabel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                    }
                    @Override
                    public void mousePressed(MouseEvent e) { 
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) { 
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                       jLabel.setBackground(new Color(45, 51, 61));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                       jLabel.setBackground(new Color(0,0,0));
                    }
                });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        lblBus = new javax.swing.JLabel();
        lblPassenger = new javax.swing.JLabel();
        lblPassengerDetailes = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblBusDetailes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalEarnings = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalBuses = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPassengers = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/image/buslogo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 180));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Registration_45px.png"))); // NOI18N
        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });
        jPanel8.add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 70));

        lblBus.setForeground(new java.awt.Color(255, 255, 255));
        lblBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Home_45px_1.png"))); // NOI18N
        lblBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusMouseClicked(evt);
            }
        });
        jPanel8.add(lblBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 70));

        lblPassenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Ticket_Purchase_45px.png"))); // NOI18N
        lblPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 70));

        lblPassengerDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassengerDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_User_Account_45px_1.png"))); // NOI18N
        lblPassengerDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassengerDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 120, 70));

        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Numbered_List_45px.png"))); // NOI18N
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });
        jPanel8.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 70));

        lblBusDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Bus_50px_2.png"))); // NOI18N
        lblBusDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblBusDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 70));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 540));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 540));

        jPanel2.setBackground(new java.awt.Color(34, 39, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Over View");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Show all taks");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 40));

        jPanel6.setBackground(new java.awt.Color(45, 51, 61));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Average_2_100px.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 90));

        lblTotalEarnings.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblTotalEarnings.setForeground(new java.awt.Color(204, 204, 204));
        lblTotalEarnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalEarnings.setText("0");
        jPanel6.add(lblTotalEarnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 70));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Earnings");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 300, 360));

        jPanel5.setBackground(new java.awt.Color(45, 51, 61));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Bus_80px.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 90));

        lblTotalBuses.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblTotalBuses.setForeground(new java.awt.Color(204, 204, 204));
        lblTotalBuses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalBuses.setText("0");
        jPanel5.add(lblTotalBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Buses");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 300, 360));

        jPanel3.setBackground(new java.awt.Color(45, 51, 61));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_User_Groups_80px.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 100));

        lblTotalPassengers.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblTotalPassengers.setForeground(new java.awt.Color(204, 204, 204));
        lblTotalPassengers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPassengers.setText("0");
        jPanel3.add(lblTotalPassengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 70));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Passengers");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 300, 360));

        btnGo.setBackground(new java.awt.Color(0, 0, 0));
        btnGo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGo.setForeground(new java.awt.Color(204, 204, 204));
        btnGo.setText("Continue");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        jPanel2.add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 620, 130, 40));

        jPanel11.setBackground(new java.awt.Color(45, 51, 61));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(45, 51, 61));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1160, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
       new TicketBookingView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGoActionPerformed

    private void lblBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusMouseClicked
        this.setVisible(true);
    }//GEN-LAST:event_lblBusMouseClicked

    private void lblPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerMouseClicked
        new TicketBookingView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPassengerMouseClicked

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
         new RegistrationFormView().setVisible(true);
    }//GEN-LAST:event_lblRegistrationMouseClicked

    private void lblPassengerDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerDetailesMouseClicked
        new PassengerDetailesView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblPassengerDetailesMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        new AllDetails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblBusDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusDetailesMouseClicked
       new BusDetailesView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblBusDetailesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblBus;
    private javax.swing.JLabel lblBusDetailes;
    private javax.swing.JLabel lblPassenger;
    private javax.swing.JLabel lblPassengerDetailes;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblTotalBuses;
    private javax.swing.JLabel lblTotalEarnings;
    private javax.swing.JLabel lblTotalPassengers;
    // End of variables declaration//GEN-END:variables

    private void loadAllPassengerCount() {
       try {
            
            int passengerCount=new DashBoardController().passengerCount();
            lblTotalPassengers.setText(String.valueOf(passengerCount));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllBusCount() {
        try {
            
            int busCount=new DashBoardController().getbusCount();
            lblTotalBuses.setText(String.valueOf(busCount));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllEarningCount() {
        try {
            
            double earningSum=new DashBoardController().getEarning();
            lblTotalEarnings.setText(String.valueOf(earningSum));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
