
package lk.ijse.bus_seat_reservation.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.bus_seat_reservation.controller.LogInController;

public class LogInView extends javax.swing.JFrame {

    public LogInView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblGoodMorning2 = new javax.swing.JLabel();
        lblGoodMorning5 = new javax.swing.JLabel();
        lblGoodMorning1 = new javax.swing.JLabel();
        lblGoodMorning3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        lblGoodMorning4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblGoodMorning = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblUserNameMess = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 20, 20));

        lblGoodMorning2.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning2.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning2.setText("Form");
        jPanel1.add(lblGoodMorning2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 100, -1));

        lblGoodMorning5.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning5.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning5.setText("Login");
        jPanel1.add(lblGoodMorning5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 100, -1));

        lblGoodMorning1.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning1.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning1.setText("Highway ");
        jPanel1.add(lblGoodMorning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, -1));

        lblGoodMorning3.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning3.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning3.setText("Seats");
        jPanel1.add(lblGoodMorning3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 330, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Lock_50px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 50));

        pfPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 330, 40));

        lblGoodMorning4.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning4.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning4.setText("Reservation");
        jPanel1.add(lblGoodMorning4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 240, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SHOW");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 20));

        lblPassword.setForeground(java.awt.Color.red);
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 345, 17));

        lblGoodMorning.setBackground(new java.awt.Color(0, 0, 0));
        lblGoodMorning.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblGoodMorning.setForeground(new java.awt.Color(255, 255, 255));
        lblGoodMorning.setText(" Bus ");
        jPanel1.add(lblGoodMorning, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Log in to your Account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 270, 70));

        jButton1.setBackground(new java.awt.Color(34, 39, 46));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        lblUserNameMess.setForeground(java.awt.Color.red);
        jPanel1.add(lblUserNameMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 345, 17));

        jButton2.setBackground(new java.awt.Color(34, 39, 46));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.setAlignmentX(0.5F);
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Key_2_45px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Male_User_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/image/logingImage.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 680, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getUserNameAndPassword();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGoodMorning;
    private javax.swing.JLabel lblGoodMorning1;
    private javax.swing.JLabel lblGoodMorning2;
    private javax.swing.JLabel lblGoodMorning3;
    private javax.swing.JLabel lblGoodMorning4;
    private javax.swing.JLabel lblGoodMorning5;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserNameMess;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void getUserNameAndPassword() {
        try {
            
            String userNameUI=txtUserName.getText().trim();
            String userPasswordUI = pfPassword.getText().trim();
            boolean result=new LogInController().getUserNamePassword(userNameUI,userPasswordUI);
            
            if(result=true){
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                new DashBoardView().setVisible(true);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Username and Password not Matched");
                txtUserName.setText("");
                pfPassword.setText("");
                
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LogInView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LogInView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
