
package lk.ijse.bus_seat_reservation.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.bus_seat_reservation.controller.PassengerInformationController;
import lk.ijse.bus_seat_reservation.modal.PassengerInformation;

public class PassengerInformationView extends javax.swing.JFrame {

    public PassengerInformationView() {
        initComponents();
        setPassengerId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPassInformationId = new javax.swing.JTextField();
        txtPassNIC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPassPhone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPassName = new javax.swing.JTextField();
        btnPassInformationSave = new javax.swing.JButton();
        btnPassInformationReset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(45, 51, 61));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(45, 51, 61));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Passenger ID");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel15.setBackground(new java.awt.Color(45, 51, 61));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Name");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtPassInformationId.setBackground(new java.awt.Color(204, 204, 204));
        txtPassInformationId.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassInformationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassInformationIdActionPerformed(evt);
            }
        });
        jPanel11.add(txtPassInformationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 236, 30));

        txtPassNIC.setBackground(new java.awt.Color(204, 204, 204));
        txtPassNIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNICActionPerformed(evt);
            }
        });
        jPanel11.add(txtPassNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 236, 30));

        jLabel16.setBackground(new java.awt.Color(45, 51, 61));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("NIC");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtPassPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPassPhone.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassPhoneActionPerformed(evt);
            }
        });
        jPanel11.add(txtPassPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 236, 30));

        jLabel17.setBackground(new java.awt.Color(45, 51, 61));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Phone Number");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtPassName.setBackground(new java.awt.Color(204, 204, 204));
        txtPassName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtPassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNameActionPerformed(evt);
            }
        });
        jPanel11.add(txtPassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 236, 30));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 440, 310));

        btnPassInformationSave.setBackground(new java.awt.Color(0, 0, 0));
        btnPassInformationSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPassInformationSave.setForeground(new java.awt.Color(204, 204, 204));
        btnPassInformationSave.setText("Save");
        btnPassInformationSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassInformationSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassInformationSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, 40));

        btnPassInformationReset.setBackground(new java.awt.Color(0, 0, 0));
        btnPassInformationReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPassInformationReset.setForeground(new java.awt.Color(204, 204, 204));
        btnPassInformationReset.setText("Reset");
        btnPassInformationReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassInformationResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassInformationReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Passenger Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 290, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassInformationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassInformationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassInformationIdActionPerformed

    private void txtPassNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNICActionPerformed

    private void txtPassPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassPhoneActionPerformed

    private void btnPassInformationSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassInformationSaveActionPerformed

        try {
            String passenger_id = txtPassInformationId.getText();                                               
            String name = txtPassName.getText();
            String nic = txtPassNIC.getText();
            String phone = txtPassPhone.getText();
           
            PassengerInformation p1 = new PassengerInformation(
                passenger_id,
                name,
                nic,
                phone
            );

            boolean isSaved = new PassengerInformationController().savePassengerInformation(p1);

            if (isSaved) {
                JOptionPane.showMessageDialog(null, "Saved");
            } else {
                JOptionPane.showMessageDialog(null, "Try again");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PassengerInformationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PassengerInformationView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_btnPassInformationSaveActionPerformed

    private void btnPassInformationResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassInformationResetActionPerformed
        txtPassName.setText("");
        txtPassNIC.setText("");
        txtPassPhone.setText("");
    }//GEN-LAST:event_btnPassInformationResetActionPerformed

    private void txtPassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNameActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      
       
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassInformationReset;
    private javax.swing.JButton btnPassInformationSave;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JTextField txtPassInformationId;
    private javax.swing.JTextField txtPassNIC;
    private javax.swing.JTextField txtPassName;
    private javax.swing.JTextField txtPassPhone;
    // End of variables declaration//GEN-END:variables

    private void setPassengerId() {
        try {
            
            String passenger_id = new PassengerInformationController().getPassengerId();
            txtPassInformationId.setText(passenger_id);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PassengerInformationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PassengerInformationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
