
package lk.ijse.bus_seat_reservation.view;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.bus_seat_reservation.controller.TicketBookingController;
import lk.ijse.bus_seat_reservation.modal.BusSchedule;
import lk.ijse.bus_seat_reservation.modal.BusSeat;
import lk.ijse.bus_seat_reservation.modal.Reservation;
import lk.ijse.bus_seat_reservation.modal.SeatReservation;

public class TicketBookingView extends javax.swing.JFrame {
    //SeatBookingView se=new SeatBookingView();
    
    public TicketBookingView() {
        initComponents();
        setReservationIdAndDateTime();
       
        JLabel[] lbl={lblRegistration,lblBus,lblPassenger,lblReport,lblPassengerDetailes,lblBusDetailes};
        for (JLabel jLabel : lbl) {
                jLabel.setBackground(new Color(0,0,0));
                jLabel.setOpaque(true);
                jLabel.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {  
                    }
                    @Override
                    public void mousePressed(MouseEvent e) { 
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) { 
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                       jLabel.setBackground(new Color(45, 51, 61));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                       jLabel.setBackground(new Color(0,0,0));
                    }
                });
        }
    }
     public void Load(){
         try {
            String busid = txtSelectBus.getText();
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String date=format1.format(txtDate.getDate());
            
            //String date=lblDate.getText();
            List<BusSeat> busSeat = new TicketBookingController().getBusSeat(busid,date);

            DefaultTableModel modal = (DefaultTableModel) tblBusSeatId.getModel();

            for (BusSeat tempBusSeat : busSeat) {

                modal.addRow(new Object[]{
                    tempBusSeat.getSeat_id(),
                    tempBusSeat.getBus_id(),
                    tempBusSeat.getStatus(),
                    tempBusSeat.getDate() 
                });
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        lblBus = new javax.swing.JLabel();
        lblPassenger = new javax.swing.JLabel();
        lblPassengerDetailes = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblBusDetailes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOfficerId = new javax.swing.JTextField();
        txtBookingId = new javax.swing.JTextField();
        txtPassengerId = new javax.swing.JTextField();
        cmbFrom = new javax.swing.JComboBox<>();
        cmbTo = new javax.swing.JComboBox<>();
        txtSelectBus = new javax.swing.JTextField();
        btnFindBus = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBusScedule = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnFindSeat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusSeatId = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblSelectedSeat = new javax.swing.JLabel();
        txtBookingSeatQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblPricePerSeat = new javax.swing.JPanel();
        lblFare = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblTotalPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/image/buslogo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 180));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Registration_45px.png"))); // NOI18N
        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });
        jPanel8.add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 70));

        lblBus.setForeground(new java.awt.Color(255, 255, 255));
        lblBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Home_45px_1.png"))); // NOI18N
        lblBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusMouseClicked(evt);
            }
        });
        jPanel8.add(lblBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, 70));

        lblPassenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Ticket_Purchase_45px.png"))); // NOI18N
        lblPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 70));

        lblPassengerDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassengerDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_User_Account_45px_1.png"))); // NOI18N
        lblPassengerDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPassengerDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblPassengerDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 120, 70));

        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Numbered_List_45px.png"))); // NOI18N
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });
        jPanel8.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 70));

        lblBusDetailes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusDetailes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Bus_50px_2.png"))); // NOI18N
        lblBusDetailes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusDetailesMouseClicked(evt);
            }
        });
        jPanel8.add(lblBusDetailes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 70));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 540));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 770));

        jPanel2.setBackground(new java.awt.Color(34, 39, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(34, 39, 46));
        jPanel7.setPreferredSize(new java.awt.Dimension(1160, 720));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Seats");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Officer Id");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Booking Id");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Passenger Id");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 130, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Date Of Travel");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("From");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("To");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Select Bus");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtOfficerId.setBackground(new java.awt.Color(225, 225, 225));
        txtOfficerId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtOfficerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 180, 30));

        txtBookingId.setBackground(new java.awt.Color(225, 225, 225));
        txtBookingId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBookingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookingIdActionPerformed(evt);
            }
        });
        jPanel7.add(txtBookingId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 180, 30));

        txtPassengerId.setBackground(new java.awt.Color(225, 225, 225));
        txtPassengerId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassengerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassengerIdActionPerformed(evt);
            }
        });
        jPanel7.add(txtPassengerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 110, 30));

        cmbFrom.setBackground(new java.awt.Color(204, 204, 204));
        cmbFrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombo", "Galle", "Matara", "Ambalangoda" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });
        jPanel7.add(cmbFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 30));

        cmbTo.setBackground(new java.awt.Color(204, 204, 204));
        cmbTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambalangoda", "Galle", "Matara", "Beliaththa", "Hambanthota" }));
        cmbTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbToActionPerformed(evt);
            }
        });
        jPanel7.add(cmbTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, 30));

        txtSelectBus.setBackground(new java.awt.Color(225, 225, 225));
        txtSelectBus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSelectBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectBusActionPerformed(evt);
            }
        });
        jPanel7.add(txtSelectBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, 30));

        btnFindBus.setBackground(new java.awt.Color(0, 0, 0));
        btnFindBus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFindBus.setForeground(new java.awt.Color(204, 204, 204));
        btnFindBus.setText("Find Bus");
        btnFindBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBusActionPerformed(evt);
            }
        });
        jPanel7.add(btnFindBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 130, 40));

        jPanel12.setBackground(new java.awt.Color(45, 51, 61));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(45, 51, 61));
        lblTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(204, 204, 204));
        jPanel12.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 40, 180, 40));

        tblBusScedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus_Shedule_Id", "Bus_Id", "Dep.Place", "Arr.Place", "Dep.Time", "Arr.Time", "Fare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBusScedule.setFocusable(false);
        tblBusScedule.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblBusScedule.setRowHeight(25);
        tblBusScedule.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblBusScedule.setShowVerticalLines(false);
        tblBusScedule.getTableHeader().setReorderingAllowed(false);
        tblBusScedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusSceduleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBusScedule);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 690, 360));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/bus_seat_reservation/icon/icons8_Plus_Math_30px_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 40, 30));

        txtDate.setBackground(new java.awt.Color(204, 204, 204));
        txtDate.setDateFormatString("yyyy-MM-dd");
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Load Seats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 170, 130, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ticket Booking");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bus Shedule");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 40));

        btnFindSeat.setBackground(new java.awt.Color(0, 0, 0));
        btnFindSeat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFindSeat.setForeground(new java.awt.Color(204, 204, 204));
        btnFindSeat.setText("Find Seat");
        btnFindSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSeatActionPerformed(evt);
            }
        });
        jPanel7.add(btnFindSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 110, 130, 40));

        tblBusSeatId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat ID", "Bus ID", "Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBusSeatId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusSeatIdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusSeatId);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 430, 420));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Selected Seat");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Booking Seat Qty");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 630, -1, -1));

        jPanel16.setBackground(new java.awt.Color(45, 51, 61));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectedSeat.setBackground(new java.awt.Color(45, 51, 61));
        lblSelectedSeat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSelectedSeat.setForeground(new java.awt.Color(204, 204, 204));
        jPanel16.add(lblSelectedSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 570, 270, 30));

        txtBookingSeatQty.setBackground(new java.awt.Color(45, 51, 61));
        txtBookingSeatQty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBookingSeatQty.setForeground(new java.awt.Color(204, 204, 204));
        txtBookingSeatQty.setBorder(null);
        txtBookingSeatQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookingSeatQtyActionPerformed(evt);
            }
        });
        jPanel7.add(txtBookingSeatQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 270, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Price per seat");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 690, -1, -1));

        lblPricePerSeat.setBackground(new java.awt.Color(45, 51, 61));
        lblPricePerSeat.setForeground(new java.awt.Color(204, 204, 204));
        lblPricePerSeat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFare.setBackground(new java.awt.Color(45, 51, 61));
        lblFare.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFare.setForeground(new java.awt.Color(204, 204, 204));
        lblPricePerSeat.add(lblFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        jPanel7.add(lblPricePerSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 690, 270, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Total price");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 750, -1, -1));

        jPanel15.setBackground(new java.awt.Color(45, 51, 61));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(204, 204, 204));
        jPanel15.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Rs:");
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 750, 270, 30));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 204));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel7.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 670, 100, 40));

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(204, 204, 204));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel7.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 740, 100, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 950));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1710, 950));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookingIdActionPerformed

    private void txtPassengerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassengerIdActionPerformed

    }//GEN-LAST:event_txtPassengerIdActionPerformed

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFromActionPerformed

    private void cmbToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbToActionPerformed

    private void txtSelectBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectBusActionPerformed

    private void btnFindBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBusActionPerformed
        //load All Bus Schedule
        try {

            String from = cmbFrom.getSelectedItem().toString();
            String to = cmbTo.getSelectedItem().toString();

            List<BusSchedule> busSchedule = new TicketBookingController().getAllSelectedBusSchedule(from,to);

            DefaultTableModel modal = (DefaultTableModel) tblBusScedule.getModel();

            for (BusSchedule tempBusSchedule : busSchedule) {

                modal.addRow(new Object[]{
                    tempBusSchedule.getShedule_id(),
                    tempBusSchedule.getBus_id(),
                    tempBusSchedule.getDepature_place(),
                    tempBusSchedule.getArrival_place(),
                    tempBusSchedule.getDepature_time(),
                    tempBusSchedule.getArrival_time(),
                    tempBusSchedule.getFare()
                });
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFindBusActionPerformed

    private void tblBusSceduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusSceduleMouseClicked
        
        int selectedRow = tblBusScedule.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblBusScedule.getModel();   
        txtSelectBus.setText(model.getValueAt(selectedRow, 1).toString());
        lblFare.setText(model.getValueAt(selectedRow, 6).toString());
        
    }//GEN-LAST:event_tblBusSceduleMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new PassengerInformationView().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 1; i <=20; i++) {
            
        
        try {
            String busid = txtSelectBus.getText();
            
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String date=format1.format(txtDate.getDate());
          boolean set =new TicketBookingController().loadSeat(busid,date);
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }
             }   
      
         JOptionPane.showMessageDialog(null, "Seats Loaded");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFindSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSeatActionPerformed

        Load();
       
    }//GEN-LAST:event_btnFindSeatActionPerformed

    private void tblBusSeatIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusSeatIdMouseClicked
      
        try {
            int selectedRow = tblBusSeatId.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblBusSeatId.getModel();
            
            lblSelectedSeat.setText(model.getValueAt(selectedRow, 0).toString());

          int select=tblBusSeatId.getSelectedRow();           
          String seatId=model.getValueAt(select,0).toString();          
          String date=model.getValueAt(select,3).toString();

           boolean change = new TicketBookingController().setstatus(seatId,date);

          if (change) {
                //Load();

          } else {
                //JOptionPane.showMessageDialog(null, "Seat is alredy Booked");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblBusSeatIdMouseClicked

    private void txtBookingSeatQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookingSeatQtyActionPerformed
        
        getTotalPrice();

    }//GEN-LAST:event_txtBookingSeatQtyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed


        try {
            //boolean isSaved = new TicketBookingController().saveSeatReservation(r1);
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String date=format1.format(txtDate.getDate());

            int index=tblBusScedule.getSelectedRow();
            TableModel mode=tblBusScedule.getModel();

            String reservation_id = txtBookingId.getText();
            String officer_id = txtOfficerId.getText();
            String passenger_id = txtPassengerId.getText();
            String reservation_date = format1.format(txtDate.getDate());
            String shedule_id = mode.getValueAt(index, 0).toString();

            DefaultTableModel model = (DefaultTableModel) tblBusSeatId.getModel();
            int selected=tblBusSeatId.getSelectedRow();
            String seat_id=lblSelectedSeat.getText();
            String booking_date= format1.format(txtDate.getDate());
            String status=model.getValueAt(selected,2).toString();
            String number_of_reseved_seat=txtBookingSeatQty.getText();
            String price=lblTotalPrice.getText();

            ArrayList<SeatReservation> list= new ArrayList();
            list.add(new SeatReservation(
                reservation_id,
                seat_id,
                booking_date,
                status,
                number_of_reseved_seat,
                price));

        Reservation r2 = new Reservation(
            reservation_id,
            officer_id,
            passenger_id,
            reservation_date,
            shedule_id,
            list
        );

        boolean isSaved = new TicketBookingController().saveReservation(r2);

        if (isSaved) {
            JOptionPane.showMessageDialog(null, "Saved");
        } else {
            JOptionPane.showMessageDialog(null, "Try again");
        }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lblSelectedSeat.setText(null);
        txtBookingSeatQty.setText(null);
        lblTotalPrice.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
        new RegistrationFormView().setVisible(true);
      
    }//GEN-LAST:event_lblRegistrationMouseClicked

    private void lblBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusMouseClicked
        new DashBoardView().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_lblBusMouseClicked

    private void lblPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerMouseClicked
         this.setVisible(true);
       
    }//GEN-LAST:event_lblPassengerMouseClicked

    private void lblPassengerDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPassengerDetailesMouseClicked
         new PassengerDetailesView().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblPassengerDetailesMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        new AllDetails().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblBusDetailesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusDetailesMouseClicked
        new BusDetailesView().setVisible(true);
         this.dispose();
      
    }//GEN-LAST:event_lblBusDetailesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBookingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindBus;
    private javax.swing.JButton btnFindSeat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBus;
    private javax.swing.JLabel lblBusDetailes;
    public javax.swing.JLabel lblFare;
    private javax.swing.JLabel lblPassenger;
    private javax.swing.JLabel lblPassengerDetailes;
    private javax.swing.JPanel lblPricePerSeat;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSelectedSeat;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTable tblBusScedule;
    private javax.swing.JTable tblBusSeatId;
    private javax.swing.JTextField txtBookingId;
    private javax.swing.JTextField txtBookingSeatQty;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtOfficerId;
    private javax.swing.JTextField txtPassengerId;
    private javax.swing.JTextField txtSelectBus;
    // End of variables declaration//GEN-END:variables

   
    private void setReservationIdAndDateTime() {
         try {

            String reservation_id = new TicketBookingController().getBookingId();
            txtBookingId.setText(reservation_id);
            
            Date date = new Date();
            SimpleDateFormat format1 = new SimpleDateFormat("YYYY-MM-dd");
            txtDate.setDate(date);

            SimpleDateFormat format2 = new SimpleDateFormat("HH:mm:ss");
            lblTime.setText(format2.format(date));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TicketBookingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getTotalPrice(){
        
       double bookingSeatQty = Double.parseDouble(txtBookingSeatQty.getText());
       double pricePerSeat =Double.parseDouble(lblFare.getText());   
       double totalPrice=bookingSeatQty*pricePerSeat;
       lblTotalPrice.setText(String.valueOf(totalPrice)); 
    
   } 

    
}

